name: ch0202 Issue assignment
# 参考： https://github.com/marketplace/actions/create-an-issue
# 暂时没有弄明白
on:
    issues:
        types: [opened]
jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1.0.3
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  assignees: testesdapri
